<?php

namespace ContainerWlRWBtQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEleveService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.u5NeONy.App\Entity\Eleve' shared service.
     *
     * @return \App\Entity\Eleve
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.u5NeONy": it references class "App\\Entity\\Eleve" but no such service exists.');
    }
}
