<?php

namespace ContainerY4LSwwC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCoursModifierTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\CoursModifierType' shared autowired service.
     *
     * @return \App\Form\CoursModifierType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/CoursModifierType.php';

        return $container->privates['App\\Form\\CoursModifierType'] = new \App\Form\CoursModifierType();
    }
}
