<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWlRWBtQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWlRWBtQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWlRWBtQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWlRWBtQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWlRWBtQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'WlRWBtQ',
    'container.build_id' => 'c6986f61',
    'container.build_time' => 1650545817,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWlRWBtQ');
