<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHEDUITR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHEDUITR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHEDUITR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHEDUITR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHEDUITR\App_KernelDevDebugContainer([
    'container.build_hash' => 'HEDUITR',
    'container.build_id' => '69982479',
    'container.build_time' => 1639558200,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHEDUITR');
